[package]
name = "aptos-pump-fun"
version = "1.0.0"
authors = []

[addresses]
pump = "480abb076349c0e6cffbbd762e13bb75c2c08d01359eff05e199e4fae02ab7fe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.amm-v1]
local = "../razor/"

[dev-dependencies]
