[package]
name = "aptos-pump-fun"
version = "1.0.0"
upgrade_policy = "compatible"


[addresses]
pump = "3e2cdfa1a2899d13211aec36b76e8d99ddc3db167b713eb7b58c30bfbf95cf86"
fee_address = "0xe6654beebe136db3b6f3cd5b1f121ef04f013f3f24df58d0806dd97086c6e6cf"
razor_amm = "0xc4e68f29fa608d2630d11513c8de731b09a975f2f75ea945160491b9bfd36992"
razor_libs = "0x16f014d37f7d8455c49d587bfc93a26eba6e3f02f1eb391e6afa620b8ffdd91d"
move_metadata_address = "0xa"

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
AptosStdlib = { local = "../framework/aptos-stdlib" }
RazorAmm = { local = "../RazorAmm/" }
RazorLibs = { git = "https://github.com/razorlabsorg/razor-libs.git", rev="main" }

