[package]
name = "aptos-pump-fun"
version = "1.0.0"
upgrade_policy = "compatible"


[addresses]
pump = "e5be3f8decdc1a8c4f5d032730b7ef71cf86c057003f86232e89c821321a63b4"
razor_amm = "0xc4e68f29fa608d2630d11513c8de731b09a975f2f75ea945160491b9bfd36992"
razor_libs = "0x16f014d37f7d8455c49d587bfc93a26eba6e3f02f1eb391e6afa620b8ffdd91d"

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
AptosStdlib = { local = "../framework/aptos-stdlib" }
RazorAmm = { local = "../RazorAmm/" }
RazorLibs = { git = "https://github.com/razorlabsorg/razor-libs.git", rev="main" }

